name: uptown
favicon: null
layout_spectrum: 0.48573
typography_spectrum: 0.18678935919888318
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3dc1c3'
    - '#ffffff'
    - '#d8f0f0'
    - '#91d9db'
    - '#58c7ca'
  brandStrength: 0.15862285974435508
  lightness: 0.4260366961825639
  saturation: 0.806188897928223
  rhythmicContrast: 0.4982131193391979
purpose: []
