name: uptown
favicon: null
layout_spectrum: 0.50429
typography_spectrum: 0.16013
title: inteligencia digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#736e6b'
    - '#3dc1c3'
    - '#a6a0a0'
    - '#8fdadc'
  brandStrength: 0.15862285974435508
  lightness: 0.4260366961825639
  saturation: 0.806188897928223
  rhythmicContrast: 0.4982131193391979
purpose: []
